### ISSUE TITLE
Add inline log message

### ISSUE THREAD

**Issue by Polpetta** [apontini/jirawatch#5]
It would be cool to add a new flag, let's say `-m` (totally not copying from git) that lets you insert the message without opening the editor.
Something like:
```sh
jirawatch track SOMETHING-123 -m"Fix tests"
```
When you hit `Ctrl-C` no editor should open, and the "Fix tests" message should be automatically pushed in the Jira log work section.

**Comment by apontini** [comment]
That's nice, I'll introduce it with the next update

**Comment by apontini** [comment]
This has been implemented
